import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))

// Single oxlint config
export default {
  plugins: [
    'typescript',
    'react',
    'react-perf',
    'jsx-a11y',
    'import',
    'unicorn',
    'oxc',
    'promise',
  ],
  jsPlugins: [
    { name: '@tanstack/query', specifier: '@tanstack/eslint-plugin-query' },
    {
      name: 'react-you-might-not-need-an-effect',
      specifier: 'eslint-plugin-react-you-might-not-need-an-effect',
    },
    { name: 'react-hooks-js', specifier: 'eslint-plugin-react-hooks' },
  ],
  categories: {
    correctness: 'error',
    suspicious: 'warn',
    perf: 'warn',
  },
  env: {
    browser: true,
    node: true,
    es2020: true,
  },
  settings: {
    react: {
      version: '19.2',
    },
  },
  options: {
    typeAware: true,
  },
  ignorePatterns: [
    '**/node_modules/',
    '**/dist',
    '**/build',
    '**/.tanstack',
    '*.config.{js,ts,mjs,cjs}',
    'oxlint.config.ts',
    'vite.config.ts',
    '*.gen.ts',
  ],
  rules: {
    // 'no-console': 'warn',

    'typescript/no-explicit-any': 'error',
    'typescript/no-non-null-assertion': 'off',
    'typescript/no-unused-vars': [
      'warn',
      {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      },
    ],
    'typescript/consistent-type-imports': [
      'error',
      {
        prefer: 'type-imports',
        disallowTypeAnnotations: false,
        fixStyle: 'separate-type-imports',
      },
    ],
    'typescript/ban-ts-comment': [
      'error',
      {
        minimumDescriptionLength: 10,
      },
    ],
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-dynamic-delete': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-extraneous-class': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-nullish-coalescing': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-literal-enum-member': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/triple-slash-reference': 'error',

    // Type-aware: keep only no-deprecated; the rest are disabled to match the
    // project's prior behavior (enable later as a deliberate opt-in).
    'typescript/no-deprecated': 'warn',
    'typescript/no-floating-promises': 'off',
    'typescript/no-misused-promises': 'off',
    'typescript/no-unsafe-assignment': 'off',
    'typescript/no-unsafe-member-access': 'off',
    'typescript/no-unsafe-call': 'off',
    'typescript/no-unsafe-return': 'off',
    'typescript/no-unsafe-argument': 'off',
    'typescript/no-unsafe-type-assertion': 'off',
    'typescript/no-unnecessary-type-assertion': 'off',
    'typescript/no-unnecessary-type-arguments': 'off',
    'typescript/no-unnecessary-type-conversion': 'off',
    'typescript/no-unnecessary-type-parameters': 'off',
    'typescript/no-unnecessary-boolean-literal-compare': 'off',
    'typescript/no-unnecessary-template-expression': 'off',
    'typescript/no-base-to-string': 'off',
    'typescript/no-useless-default-assignment': 'off',
    'typescript/await-thenable': 'off',
    'typescript/restrict-template-expressions': 'off',
    'typescript/restrict-plus-operands': 'off',
    'typescript/no-redundant-type-constituents': 'off',
    'typescript/no-duplicate-type-constituents': 'off',
    'typescript/unbound-method': 'off',
    'typescript/no-unsafe-enum-comparison': 'off',
    'typescript/consistent-return': 'off',
    'typescript/no-for-in-array': 'off',
    'typescript/no-implied-eval': 'off',
    'typescript/no-array-delete': 'off',
    'typescript/no-confusing-void-expression': 'off',
    'typescript/no-meaningless-void-operator': 'off',
    'typescript/no-mixed-enums': 'off',
    'typescript/non-nullable-type-assertion-style': 'off',
    'typescript/prefer-promise-reject-errors': 'off',
    'typescript/prefer-reduce-type-parameter': 'off',
    'typescript/prefer-return-this-type': 'off',
    'typescript/require-array-sort-compare': 'off',
    'typescript/use-unknown-in-catch-callback-variable': 'off',

    'react/jsx-key': 'error',
    'react/jsx-no-comment-textnodes': 'error',
    'react/jsx-no-duplicate-props': 'error',
    'react/jsx-no-target-blank': 'error',
    'react/jsx-no-undef': 'error',
    'react/no-children-prop': 'error',
    'react/no-danger-with-children': 'error',
    'react/no-direct-mutation-state': 'error',
    'react/no-find-dom-node': 'error',
    'react/no-is-mounted': 'error',
    'react/no-render-return-value': 'error',
    'react/no-string-refs': 'error',
    'react/no-unescaped-entities': 'error',
    'react/no-unknown-property': 'error',
    'react/react-in-jsx-scope': 'off',
    'react/rules-of-hooks': 'error',
    'react/exhaustive-deps': 'warn',

    // React Compiler + hooks (eslint-plugin-react-hooks v7). rules-of-hooks and
    // exhaustive-deps are handled natively by oxlint above (faster), so disable
    // the JS-plugin duplicates here.
    'react-hooks-js/rules-of-hooks': 'off',
    'react-hooks-js/exhaustive-deps': 'off',
    'react-hooks-js/config': 'off',
    'react-hooks-js/gating': 'off',
    'react-hooks-js/static-components': 'error',
    'react-hooks-js/use-memo': 'error',
    'react-hooks-js/void-use-memo': 'error',
    'react-hooks-js/preserve-manual-memoization': 'error',
    'react-hooks-js/incompatible-library': 'warn',
    'react-hooks-js/immutability': 'error',
    'react-hooks-js/globals': 'error',
    'react-hooks-js/refs': 'error',
    'react-hooks-js/set-state-in-effect': 'error',
    'react-hooks-js/error-boundaries': 'error',
    'react-hooks-js/purity': 'error',
    'react-hooks-js/set-state-in-render': 'error',
    'react-hooks-js/unsupported-syntax': 'warn',

    'jsx-a11y/alt-text': 'error',
    'jsx-a11y/anchor-has-content': 'error',
    'jsx-a11y/anchor-is-valid': 'error',
    'jsx-a11y/aria-props': 'error',
    'jsx-a11y/aria-role': 'error',
    'jsx-a11y/click-events-have-key-events': 'error',
    'jsx-a11y/heading-has-content': 'error',
    'jsx-a11y/no-autofocus': 'warn',
    'jsx-a11y/no-redundant-roles': 'error',
    'jsx-a11y/role-has-required-aria-props': 'error',
    'jsx-a11y/tabindex-no-positive': 'error',

    'import/no-cycle': 'error',
    'import/no-self-import': 'error',
    'import/no-duplicates': 'error',
    'import/no-named-as-default': 'warn',
    'import/no-named-as-default-member': 'warn',

    'react-perf/jsx-no-new-object-as-prop': 'warn',
    'react-perf/jsx-no-new-array-as-prop': 'warn',
    'react-perf/jsx-no-new-function-as-prop': 'warn',
    'react-perf/jsx-no-jsx-as-prop': 'warn',

    'promise/catch-or-return': 'warn',
    'promise/no-nesting': 'warn',
    'promise/no-return-wrap': 'error',
    'promise/param-names': 'error',
    'promise/valid-params': 'error',

    'oxc/no-barrel-file': 'warn',
    'oxc/no-const-enum': 'warn',

    'unicorn/no-null': 'off',
    'unicorn/prefer-top-level-await': 'warn',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/prefer-string-slice': 'warn',
    'unicorn/prefer-array-find': 'warn',
    'unicorn/prefer-array-flat': 'warn',
    'unicorn/prefer-array-flat-map': 'warn',
    'unicorn/prefer-includes': 'warn',
    'unicorn/prefer-optional-catch-binding': 'warn',
    'unicorn/throw-new-error': 'error',
    'unicorn/no-useless-spread': 'warn',
    'unicorn/no-useless-promise-resolve-reject': 'warn',
    // Pulled in implicitly by categories.perf. Their autofixes break TS:
    // prefer-set-has wraps arrays in `new Set()` without updating the `T[]`
    // annotation; no-array-sort emits `.toSorted()` which is ES2023 (lib is
    // ES2022) and changes mutate-in-place semantics. Off until opted in deliberately.
    'unicorn/prefer-set-has': 'off',
    'unicorn/no-array-sort': 'off',

    'no-var': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'no-array-constructor': 'error',
    'no-useless-constructor': 'error',

    'unicorn/empty-brace-spaces': 'off',
    'unicorn/no-nested-ternary': 'off',
    'unicorn/number-literal-case': 'off',

    '@tanstack/query/exhaustive-deps': [
      'error',
      {
        allowlist: {
          variables: [
            'getTanstack',
            'putTanstack',
            'postTanstack',
            'deleteTanstack',
          ],
        },
      },
    ],
    '@tanstack/query/no-rest-destructuring': 'warn',
    '@tanstack/query/stable-query-client': 'error',
    '@tanstack/query/no-unstable-deps': 'error',
    '@tanstack/query/infinite-query-property-order': 'error',
    '@tanstack/query/no-void-query-fn': 'error',
    '@tanstack/query/mutation-property-order': 'error',

    'react-you-might-not-need-an-effect/no-derived-state': 'warn',
    'react-you-might-not-need-an-effect/no-chain-state-updates': 'warn',
    'react-you-might-not-need-an-effect/no-event-handler': 'warn',
    'react-you-might-not-need-an-effect/no-adjust-state-on-prop-change': 'warn',
    'react-you-might-not-need-an-effect/no-reset-all-state-on-prop-change':
      'warn',
    'react-you-might-not-need-an-effect/no-pass-live-state-to-parent': 'warn',
    'react-you-might-not-need-an-effect/no-pass-data-to-parent': 'warn',
    'react-you-might-not-need-an-effect/no-initialize-state': 'warn',
  },
}
